### ISSUE TITLE
Tribute.attach breaks if passed a jquery object

### ISSUE THREAD

**Issue by kball** [zurb/tribute#1]
I know Tribute doesn't require jquery, but it seems like it should play nicely with it.  If I call attach with a jquery object I get the following error:

```
tribute.js?body=1:135 Uncaught TypeError: el.hasAttribute is not a function
_attach @ tribute.js?body=1:135
attach @ tribute.js?body=1:129
```

I think the reason is Tribute is explicitly checking for NodeList instead of just accepting any array-like set of elements

**Comment by kball** [comment]
This also results in tribute breaking if passed items found by 'getElementsByClassName' which returns set with constructor HTMLCollection

**Comment by mrsweaters** [comment]
Resolved with these three commits:
https://github.com/zurb/tribute/commit/66ff94853cf2f41b1efa52128450370b6da0d818
https://github.com/zurb/tribute/commit/e1499e695ee1caa999add1ea0ad0379597b2e31f
https://github.com/zurb/tribute/commit/67c861741e37a7a45f60e4c62d231d976d21507c
