### ISSUE TITLE
How to prevent "No Match!" from popping up?

### ISSUE THREAD

**Issue by homerlex** [zurb/tribute#106]
The doc states:

```
// template for when no match is found (optional),
// If no template is provided, menu is hidden.
noMatchTemplate: null,
```
I tried setting noMatchTemplate: null but the message still comes up.

I tried something like 

```
noMatchTemplate: function () {
     return null;
}
```
but then it just pops up with an empty container.  My tribute-container ul has a border/shadow so I see the empty div.

**Comment by JohnnyFun** [comment]
workaround:

.no-match {
	display:none;
}

**Comment by gandhirahul** [comment]
Why don't you try something like this?

`noMatchTemplate: function () {
     return null;
}`

It worked for me.

**Comment by homerlex** [comment]
@gandhirahul Because, like I said an empty container pops (with the border/dropshadow)

**Comment by gandhirahul** [comment]
I tried with another function with _display: none_ element and it still worked fine for me.

`noMatchTemplate: () => { return '<div style="display:none"></div>';},`

Is there any chance that you have global styling on <ul> or <li> element in your code as this is how it appears in the DOM. It uses 

P.S. I returned a <div> element from noMatchTemplate. 
In general case, it's always an <li> element.

<img width="845" alt="screen shot 2018-03-22 at 23 52 36" src="https://user-images.githubusercontent.com/3170094/37804471-4d723882-2e2c-11e8-9b25-969b514c7beb.png">

**Comment by homerlex** [comment]
The problem is that my styling is on the <ul> element so that is what needs to be hidden
