### ISSUE TITLE
remove mention action

### ISSUE THREAD

**Issue by ismailhakkieren** [zurb/tribute#13]
When i add mention i add input value item.original.key but when i remove mention i want to remove this parametre how ican do it please help me

i need just like this...
document.getElementById('mainEditor').addEventListener('tribute-**removed**', function (e) {
    console.log('Text replaced by Tribute!');
});

**Comment by mrsweaters** [comment]
@ismailhakkieren So you need an event that let's you know when the mention is removed from the target element?

**Comment by ismailhakkieren** [comment]
yes it gone be perfect

**Comment by ismailhakkieren** [comment]
@mrsweaters when will you finish this enhancement

**Comment by mrsweaters** [comment]
@ismailhakkieren After looking at this, I'm not sure how I would know when a mention is removed. Once the text is replaced, it just becomes regular content in your target element. We are no longer tracking it at that point? Do you have any ideas on how to track these updates?
