### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by DexterShepherd** [zurb/tribute#132]
**How can we reproduce this bug?**

1. Step one
Go to the demo site ( https://zurb.github.io/tribute/example/ )
2. Step two
interact with the contentEditable areas and form elements

**What did you expect to happen?**
I see a working demo of the functionality
**What happened instead?**
Demo does not work

Chrome 68 on MacOS 10.13.6 

<img width="1180" alt="screen shot 2018-08-06 at 3 22 31 pm" src="https://user-images.githubusercontent.com/7800175/43743928-a3532b0a-998c-11e8-9124-80f9e590a74e.png">
<img width="1072" alt="screen shot 2018-08-06 at 3 20 15 pm" src="https://user-images.githubusercontent.com/7800175/43743934-a6d0c030-998c-11e8-87a7-ba38a1cf8e02.png">

**Comment by mrsweaters** [comment]
Thanks for reporting, must be an issue with updating Babel.

**Comment by dmfaux** [comment]
@mrsweaters Perhaps it is the merge conflict in `tribute.min.js`? This was failing some of my tests when I did an update today.

**Comment by mrsweaters** [comment]
Should be working again! Thank you guys.
