### ISSUE TITLE
tribute.min.js has merge conflicts in it in dist folder

### ISSUE THREAD

**Issue by mdhari** [zurb/tribute#139]
**How can we reproduce this bug?**

1. Download the 3.3.3 release or be on the master branch.
2. Navigate to dist/
3. Open tribute.min.js

**What did you expect to happen?**
A minified version of the library
**What happened instead?**
Seeing a merge conflict in the code file itself:
```
<<<<<<< HEAD
!function(e){i...
```
https://github.com/zurb/tribute/blob/master/dist/tribute.min.js

**Comment by mrsweaters** [comment]
Fixed! Thank you for reporting!
