### ISSUE TITLE
allowSpaces: false leaves menu open when mention started but you hit space

### ISSUE THREAD

**Issue by mdevine82** [zurb/tribute#141]
**How can we reproduce this bug?**

1.  Use the demo site [https://zurb.github.io/tribute/example/](url)
2.  Enter "@jor" follow by a space and the menu still displays "Jordan Humphreys"
3.  Keep type random text and hit enter and it will overwrite all of it.
4.  Only if you type an "@" will it redraw the mention off the new trigger

**What did you expect to happen?**
As soon as I hit space with "allowSpaces: false" the menu closes

**What happened instead?**
Menu stayed opened.  This had two issues
1.  Confusing to an end user because they would see the mention box open still
2.  If they were typing in a text area and hit Enter to go to a new line it would overwrite their text with the mention.

Thanks

**Comment by fishgrind** [comment]
I created a pull request (https://github.com/zurb/tribute/pull/161) meanwhile you can use my fork, although it has another pull request open on it too (https://github.com/zurb/tribute/pull/160) but that shouldnt be a problem

**Comment by fishgrind** [comment]
found out my pull request doesn't work on Android devices because they don't send keycodes apart from keycode 225. Working on a solution for this and will add a new pull request soon.

**Comment by fishgrind** [comment]
pull request updated and tested on android

**Comment by mrsweaters** [comment]
Merged!
