### ISSUE TITLE
Add a "nothingFound" event

### ISSUE THREAD

**Issue by mattschwarz** [zurb/tribute#15]
It would be great if an event was fired when a user tried to search something and there were no matches in the collection. When trying to be judicious about sending large collections to the client, having this event could let us update the list on the fly with another large page of data without loading it all up front.

**Comment by mrsweaters** [comment]
This seems reasonable to me. Currently I'm hiding the menu when there is nothing found in the collection. Will this conflict with your goal?
https://github.com/zurb/tribute/blob/master/js/tribute.js#L197

**Comment by mattschwarz** [comment]
Good question, it would be nice to be able to keep the menu available even when there is no result to give the event enough time to load another collection. Perhaps a loading state is in order?

**Comment by mattschwarz** [comment]
To expand on that last thought: my project has a custom loading `.gif` and it would be great to display that in the menu as a dummy list item while the other collection loads. You could possible also have a config option to keep the list hidden for those who don't care about a loading state like me :)

**Comment by mrsweaters** [comment]
This makes sense, so maybe if you define an `noMatchTemplate` function we then load that  instead of hiding the list?

**Comment by mattschwarz** [comment]
That would be great!

**Comment by mrsweaters** [comment]
Please test this pull request: https://github.com/zurb/tribute/pull/17

**Comment by mattschwarz** [comment]
Looking good so far, just a couple things I've noticed based on how I think it should work:
- After the collection is updated inside the `tribute-no-match` event, the list continues to render the `noMatchTemplate` instead of updating to show new results.
- When you backspace to start filtering again (because the list doesn't update on its own), two lists begin to render, one behind the other.
- The enter key no longer inserts the mention, instead a mouse click is required.
- It seems the event fires at least twice when there is no match, but that could be a symptom of my code. Below is some pseudo code that mimics what I'm doing.

```js
var t = new Tribute({
            values: window.mentions,
            menuItemTemplate: function (item) {
                return '<li>' + item + '</li>';
            },
            noMatchTemplate: function (tribute) {
                return '<li>No match</li>';
            },
            selectClass: 'selected',
        });

        // bind to element
        t.attach(element);

        // if no match is found, request another page and update list
        element.addEventListener('tribute-no-match', function(e) {
            var xhr = new XMLHttpRequest();

            // abort multiple requests
            try {
                xhr.abort();
            }
            catch(e) {}

            xhr.open('GET', '/following?action=get_following_for_mentions&get_remainder=true');
            xhr.send();

            xhr.addEventListener('load', function() {
                if (xhr.status === 200) {
                    var response = JSON.parse(xhr.response);

                    t.collection[0].values.push(response);
                }
            });
        });
```

**Comment by mrsweaters** [comment]
@mattschwarz Thank you for testing it out! I'll take a look at this today.

**Comment by mrsweaters** [comment]
@mattschwarz I have pushed up a bunch of fixes to that pull request. Along with the fixes in https://github.com/zurb/tribute/pull/18, there may be enough here for a major release. As far as the multiple calls to `no-match`, this happens because a lookup is fired on each keyup event. If collection values are being manipulated, you will have to be sure that duplicates are not inserted.

I have added the `appendCurrent(values)` and `append(index, values)` helper methods to make updating the current and arbitrary collections much easier.

**Comment by mrsweaters** [comment]
I've merged into master, seems to be working pretty well.

**Comment by mattschwarz** [comment]
Great, will test!

**Comment by anubrij** [comment]
Hi, is there any way to add the no match text in current collection or select it 
I mean suppose I write #thisIsHash and that is not in the value list , still want to have possibility to select this

**Comment by nilesh-spotdraft** [comment]
How can we add click event on image in noMatchTemplate function template in angular?
**noMatchTemplate: function(item) { return '<li id="noMatchTemplateId" style="color: #21307A;width: 450px;" onclick="clickEvent()"> Invite  <img src='/assets/info.svg' alt='info'/> </li>`}**
