### ISSUE TITLE
In mobile browser, I could not remove value after mentioning in contenteditable field

### ISSUE THREAD

**Issue by alfredalfie123** [zurb/tribute#166]
**How can we reproduce this bug?**
1. Open https://zurb.github.io/tribute/example/ in **mobile browser**
2. Mention someone in contenteditable field
3. Remove this person

**What did you expect to happen?**
It should remove person.

**What happened instead?**
Could not remove person.

**Comment by thecoconutstudio** [comment]
I'm also having the same issue. It's find on iOS devices, just android

**Comment by thecoconutstudio** [comment]
@alfredalfie123 did you find a solution to this?

**Comment by alfredalfie123** [comment]
@thecoconutstudio unfortunately I can't.

**Comment by mrsweaters** [comment]
I'm not able to reproduce this. Can you test again against master? What version of Android and which browser? Thank you!

**Comment by mrsweaters** [comment]
You can now test these changes against version `3.5.0`. Let me know if you are still experiencing these issues by reopening this one.

**Comment by keligijus** [comment]
I think this is still an issue.

Demo. Tested on Android emulator, Nexus 5x, Chrome, on Tribute demo site.

When deleting characters, the contenteditable box first loses focus, then random characters are added.

![tribute-android-bug-demo](https://user-images.githubusercontent.com/6559757/57687354-fe216a80-7643-11e9-9098-48058513aa25.gif)

**Comment by daothanhloc** [comment]
@keligijus i need some code example
