### ISSUE TITLE
removing value from mentions

### ISSUE THREAD

**Issue by MrfksIv** [zurb/tribute#169]
Is there a way of removing as specific value from the list of mentions? I.e. something like the opposite of 'appendCurrent(..)'

For example, Tim is no longer part of the chatgroup and shouldn't come up in the mentions list.

**Comment by mrsweaters** [comment]
Yes! You would need to overwrite the whole values array. To do this, pass the optional `replace` boolean to `appendCurrent`.
https://github.com/zurb/tribute/blob/994fbf2d1632a383cc45f232df87e0a5ec0e21fa/src/Tribute.js#L377

```
this.tribute.appendCurrent(newValues, true);
```

Thanks for asking!
