### ISSUE TITLE
Menu outside viewport

### ISSUE THREAD

**Issue by fynnfeldpausch** [zurb/tribute#174]
**How can we reproduce this bug?**

1. Set the min-width of the menu to 300px (or add a long option to the menu)
2. Scale down to a window size of less than 300px to the right
3. Trigger a tribute

**What did you expect to happen?**
The menu is placed within the viewport.

**What happened instead?**
The menu is automatically re-positioned to the left. However, there is no space to show the tribute. It is not visible.

**Link (jsfiddle/plunkr/codepen) or Screenshot:**
<img width="516" alt="bildschirmfoto 2018-12-17 um 15 44 21" src="https://user-images.githubusercontent.com/1246913/50094195-e370d400-0212-11e9-9992-951afdc7db86.png">
<img width="423" alt="bildschirmfoto 2018-12-17 um 15 44 33" src="https://user-images.githubusercontent.com/1246913/50094199-e4a20100-0212-11e9-986e-4d913c0e934b.png">

**Comment by mrsweaters** [comment]
I was able to reproduce this, working on a fix now. Thank you!
