### ISSUE TITLE
Is there a way to choose which menu you want to show with `showMenuForCollection` when you have a tribute instance with multiple collections?

### ISSUE THREAD

**Issue by jamauro** [zurb/tribute#185]
**How can we reproduce this bug?**
1. Set up a tribute instance with multiple collections
2. Try to use showMenuForCollection(element) for the 3rd collection

**What did you expect to happen?**
I expected to be able to choose which collection I want to display.

**What happened instead?**
The menu for the first item in the collection array is shown.

What I've done as a workaround is to set up 2 tribute instances on the same contenteditable `div`. This works to show the correct menu but I get a warning in the console saying Tribute was already attached to the div.

**Comment by rcavezza** [comment]
I believe if you use `showMenuForCollection(element, 2)`, this will give you the functionality you're looking for.

**Comment by jamauro** [comment]
@rcavezza that did it. Thanks!

@mrsweaters thanks for adding this functionality. It would be great to see the Readme updated to mention that you can pass in an index for the `showMenuForCollection` function. :)
