### ISSUE TITLE
What's the best approach for performance when you have a values array with 1000+ items?

### ISSUE THREAD

**Issue by jamauro** [zurb/tribute#186]
I'd like to use Tribute for emojis. It works well except on the first load. It takes ~3 seconds to respond to the trigger. On subsequent triggers of the collection, it's great. 

I have ~1100 objects in my `values` array. Each object looks like:
```
{
  key: "smile",
  value: 🙂
}
```
Does anyone have any ideas on how to speed up the first load other than simply reducing the number of objects? 

I've attempted loading a subset when attaching the instance and then using the `append` function to load the rest but that wasn't ideal either. 

Is there a way to append more objects as the user continues to type? Or maybe some way to preload all objects?

**Comment by jamauro** [comment]
Nevermind. I think I got what I needed using the `values` function and `fuzzysort`. It would be cool if tribute offered some way to limit the amount of items that are displayed initially and then used it's own fuzzy searching magic to find the rest as the user types.

**Comment by dessalines** [comment]
@jamauro Do you have emojis working? It'd be really helpful if you posted your template here!

**Comment by jamauro** [comment]
Hey @dessalines, I think if I were to do this again, I would use the feature that was added here: https://github.com/zurb/tribute/pull/240.

My current solution looks a lot like this: https://github.com/zurb/tribute#loading-remote-data

**Comment by dessalines** [comment]
Thanks, I did find a data source, @WebReflection made a wonderful library here: https://github.com/WebReflection/emoji-short-name

Then to get it into tribute, you can just do:

```ts
    this.tribute = new Tribute({
      collection: [
        // Emojis
        {
          trigger: ':',
          menuItemTemplate: (item: any) => {
            let emoji = `:${item.original.key}:`;
            return `${item.original.val} ${emoji}`;
          },
          selectTemplate: (item: any) => {
            return `:${item.original.key}:`;
          },
          values: Object.entries(emojiShortName).map(e => {return {'key': e[1], 'val': e[0]}}),
          allowSpaces: false,
          autocompleteMode: true,
          menuItemLimit: 10,
        },
```
