### ISSUE TITLE
Item isn't inserted into contenteditable div when using `showMenuForCollection`

### ISSUE THREAD

**Issue by jamauro** [zurb/tribute#187]
**How can we reproduce this bug?**

1. Set up a Tribute instance and attach it to a `contenteditable` div. (Not sure if this is relevant but in my instance I have a selectTemplate and a menuItemTemplate defined).
2. Use the `mousedown` event on another element to call the `showMenuForCollection` as described in the docs.
3. Click one of the items shown in the menu.

**What did you expect to happen?**
The item you clicked would be inserted into the contenteditable div.

**What happened instead?**
The item wasn't inserted. The trigger remained in the div and the cursor moved to the left of the trigger. The console registers that the item you clicked was indeed selected.

**Comment by jamauro** [comment]
Anyone have any ideas on this one? Do I need to write something custom to get the item to insert into the contenteditable div when clicked? 

I've tried a few things and haven't had success.

@mrsweaters @rcavezza I would greatly appreciate any insight y'all might have. :)

**Comment by rcavezza** [comment]
@jamauro What's the return value of your `selectTemplate`. Are there any errors in the console?

**Comment by jamauro** [comment]
Right now it's ```"<span class='emoji'>"+item.original.value+"</span>"```. 

No console errors. If I put a `console.log(item.original.value)` in the `selectTemplate` it will register the click and return the value.

**Comment by jamauro** [comment]
I'm no longer seeing this issue after moving from v3.5 to v3.6
