### ISSUE TITLE
how to limit the amount of items that are displayed initially?

### ISSUE THREAD

**Issue by uyphanha** [zurb/tribute#188]
**How to limit the amount of items that are displayed initially?**

In my case, the people to mention is over than 100+, and I want to just display like 4-5 initially or per search.

**Comment by badz0** [comment]
@uyphanha try using `function` for `values` and there you can limit how many items you want.
Something like this:
```
values: function (text, cb) {
  cb(getItems(text).slice(0, 5))
}
```

**Comment by riophae** [comment]
I'm facing the same issue. Here is my solution:

```js
import Tribute from 'tributejs/src' // Use the ESM version, otherwise we cannot do the patch
import TributeSearch from 'tributejs/src/TributeSearch'

function patchTribute() {
  originalFilter = TributeSearch.prototype.filter

  TributeSearch.prototype.filter = function filter(...args) {
    return originalFilter.apply(this, args).slice(0, 5)
  }
}
```

**Comment by mrsweaters** [comment]
@riophae Could you add this to the Tips section of the readme?

**Comment by riophae** [comment]
@mrsweaters I think it would be better to have a new option for it :)

**Comment by mrsweaters** [comment]
@riophae Good point!

**Comment by andreynering** [comment]
I think https://github.com/zurb/tribute/pull/240 fulfils this requirement.
