### ISSUE TITLE
Do I need permissions to push up a branch?

### ISSUE THREAD

**Issue by rcavezza** [zurb/tribute#195]
Hey @mrsweaters - I'm new to open source. I made a fix and tried to push it up but I'm getting a permission denied error. Do I need to be granted permissions in order to push code? ```ERROR: Permission to zurb/tribute.git denied to rcavezza.
fatal: Could not read from remote repository.```

**Comment by mrsweaters** [comment]
No worries! You will have to create a PR. Here is a good guide on doing just that:
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/
