### ISSUE TITLE
Option to be able to delete/backspace the entire token/mention at once

### ISSUE THREAD

**Issue by moltar** [zurb/tribute#202]
Would be a good feature to be able to remove the entire at-mention with one backspace.

Right now a backspace hit for each individual character is needed.

Thanks

**Comment by mrsweaters** [comment]
You can do this by using a custom template with `contenteditable="false"`.
https://github.com/zurb/tribute#links-inside-contenteditable-are-not-clickable

**Comment by NooruddinLakhani** [comment]
ontenteditable="false" not working correctly in Android phones. It makes the keyboard down/close on focus mention tag

**Comment by NooruddinLakhani** [comment]
Any other solution ?
