### ISSUE TITLE
Ember component for Tribute 🌱

### ISSUE THREAD

**Issue by MalayaliRobz** [zurb/tribute#205]
Here is a small contribution from my side.
An **ember addon** for Tribute.

https://github.com/MalayaliRobz/ember-tribute
and the demos: https://malayalirobz.github.io/ember-tribute/docs/demos

If its all good we could add it the **Framework Support section** along with addons for other frameworks.

**Comment by mrsweaters** [comment]
Thanks @MalayaliRobz. You've been on a role! This looks great too! Feel free to add a PR to update the Readme. Thank again!
