### ISSUE TITLE
The `dist` directory was deleted

### ISSUE THREAD

**Issue by joaolavoier** [zurb/tribute#21]
Hi @mrsweaters, thanks to accept my pull-request!

But, there is anything wrong and **URGENT** to fix with the `dist` directory, I don't know if the problem was happened because i included the `dist` directory to `.gitignore`. 

I went update my TributeJS to new version on my project by **npm** and the `dist` directory disappeared.

**Comment by mrsweaters** [comment]
@joaolavoier The `dist` directory was added to the `.gitignore` file. You can just run `gulp` to rebuild it.

**Comment by mrsweaters** [comment]
oh i see. I'll add it back in.

**Comment by mrsweaters** [comment]
Fixed: https://github.com/zurb/tribute/releases/tag/2.0.1
