### ISSUE TITLE
How to search Chinese(中文) from pinyin?

### ISSUE THREAD

**Issue by imndx** [zurb/tribute#214]
The following is what I mean.

```
var tribute = new Tribute({
  values: [
    {key: '中文', value: 'cn'},
    {key: '北京', value: 'bj'}
  ]
})
```

>> The pinyin of 中文 is zhongwen, and the pinyin of 北京 is beijin

 When I input ```zhongwen``` , ```zhong``` or ```zhongw```, I want ``` {key: '中文', value: 'cn'}``` is matched,

**Comment by randolf** [comment]
Perhaps you can set the key to include the PinYin (and also ZhuYin while you're at it) alternatives, but then create a function for "menuItemTemplate" that only displays the portion up to some delimiter (space, or a colon, or whatever you decide to use).

**Comment by randolf** [comment]
Note for developers:  What would be really great is if there was support for hidden key values (if there already is, then that would be great).  Perhaps an "alt" variable could be set alongside the "key" variable that could be used to store common misspellings of words, different entry systems (such as PinYin), etc.

**Comment by imndx** [comment]
@randolf Thank you for your reply, you comment inspired me.
Finally, I find a solution, ```tribute``` already support such situation.

```
var tribute = new Tribute({
  values: [
    {key: '中文', value: 'cn', searchKey:'中文zhongwen'},
    {key: '北京', value: 'bj', searchKey:'北京beijin'}
  ],
  menuItemTemplate: function (item) {
    return item.original.key;
  }
  lookup: (item) => {
    return item.searchKey;
  }
})

```

Now when I input ```zhongwen```, ```zhongw``` or ```中```,  item ``` {key: '中文', value: 'cn', searchKey:'中文zhongwen'}``` is matched.

**Comment by randolf** [comment]
Oh, wow!  That's an even better solution!  Thanks for showing an example of how to use it (this will be helpful to me too).

**Comment by qZhiKing** [comment]
This is very NiuBi, We can combine it with pinyin(https://github.com/hotoo/pinyin)
