### ISSUE TITLE
Error while loading remote values

### ISSUE THREAD

**Issue by badz0** [zurb/tribute#224]
**How can we reproduce this bug?**

1. Open reproducing demo https://jsbin.com/vohabon/edit?html,js,output
2. Open console
3. Type `@` in textarea and during next 2sec press up or down or enter or tab button on you keyboard and see the error in console.

**What did you expect to happen?**
Expect error not happening

**What happened instead?**
Before async values were fetched tribute tried to access values.

**Link (jsfiddle/plunkr/codepen) or Screenshot:**
https://jsbin.com/vohabon/edit?html,js,output
http://prntscr.com/n31olh

**Comment by mrsweaters** [comment]
Fixed, releasing in 3.7.0
