### ISSUE TITLE
Prevent automatic trigger of new line

### ISSUE THREAD

**Issue by sgangs** [zurb/tribute#249]
As I select any option from a dropdown, it automatically creates a newline. I'm using tribute.js from jquery.

How can I make sure this doesn't happen every-time someone ends up selecting an item from the dropdown

Do note that <b>autocompleteMode</b> is <b>true</b>

**Comment by MalayaliRobz** [comment]
what is the value you gave to replaceTextSuffix: ?
might be bcoz of having replaceTextSuffix as '\n'.

**Comment by sgangs** [comment]
Dear Malayali, regret the delay. The issue was the source of data was automatically adding "\n" to it. Hence, the issue. Thanks a lot.

**Comment by sgangs** [comment]
Dear Malayali, regret the delay. The issue was the source of data was automatically adding "\n" to it. Hence, the issue. Thanks a lot.
