### ISSUE TITLE
Open and Close hooks 

### ISSUE THREAD

**Issue by shaydoc** [zurb/tribute#257]
Hey, this is another feature request, as in the ability to expose/raise `onOpen` menu and `onClose` menu hooks. What we will be looking to do is to freeze scrolling of the parent container until a mention has been selected or the tribute container has been closed.

**Comment by pavei** [comment]
Yeah! I need to hide an element when is open and show when is closed. Very nice feature!

**Comment by mxgl** [comment]
this would be very useful

**Comment by mxgl** [comment]
Is there something preventing #283 from being merged?

**Comment by mrsweaters** [comment]
Missed this one! Closing in favor of https://github.com/zurb/tribute/pull/426
