### ISSUE TITLE
Brunch Error

### ISSUE THREAD

**Issue by victorsolis** [zurb/tribute#26]
Hi. I ran into this error when I tried to use `2.0.1` with brunch `2.8.2`.

```
error: Resolving deps of node_modules/tributejs/dist/tribute.js failed. Could not load module './TributeEvents' from './node_modules/tributejs/dist'. Make sure the file actually exists.
```

Is this a brunch issue?

**Comment by jmlavoier** [comment]
@victorsolis Do you installed by npm? Try to install with `npm install git@github.com:jmlavoier/tribute.git`. Because the npm is not updated yet.

**Comment by mrsweaters** [comment]
@victorsolis @jmlavoier The new import syntax from https://github.com/zurb/tribute/pull/23 has been published to 2.0.2

**Comment by victorsolis** [comment]
I tried it again with `2.0.2` and now I'm getting this:
```
error: Resolving deps of node_modules/tributejs/dist/tribute.js failed. Improperly-cased require: './Tribute' in ./node_modules/tributejs/dist/tribute.js
```

From: https://github.com/zurb/tribute/pull/23/files#diff-1fdf421c05c1140f6d71444ea2b27638R6

**Comment by mrsweaters** [comment]
@victorsolis This should be fixed in 2.0.3, which has been published. Please test it and confirm.

**Comment by joaolavoier** [comment]
@mrsweaters I see that you changed the "main" config of package.json to fixed this, but i think it's not right. You need to keep "main" setted to compiled file. Because not all have a project to build with modules `import`, this are many people that work with `require`.

To resolve the problem of @victorsolis we need to know how is the configuration he is using, and fix the build of the lib.

**Comment by joaolavoier** [comment]
@victorsolis can you show your code, and the configuration of brunch? How is you importing the library into you project?

**Comment by mrsweaters** [comment]
@jmlavoier This makes sense. I will revert. The src folder seemed like the most sensible choice for the way I build my projects, with webpack. I'll switch it back.

**Comment by mrsweaters** [comment]
@joaolavoier I'm also having an issue implementing Tribute in my Webpack project. I'm getting this error:

```js
Uncaught SyntaxError: Unexpected token import
```

This occurred on line 6 of index.js:

```js
import Tribute from "./Tribute";
```

Are there additional dependencies that I need to get this to work? I'm already using the `import` syntax in my project.

**Comment by mrsweaters** [comment]
Oh, nevermind. I was unintentionally excluding it in my `webpack.config.js`. Updated the babel Webpack configuration to this:

```js
{
    test: /\.js$/,
    loader: 'babel',
    exclude: /node_modules\/(?!tributejs)/
}
```

All is good now!

**Comment by joaolavoier** [comment]
Nice @mrsweaters! you need to exclude node_modules on webpack. 
I thought that you was importing with something as `import Tribute from "tributejs/src/index";

But you already found the problem, that's right!

Wouldn't better write in doc this observation?

**Comment by mrsweaters** [comment]
@joaolavoier I'll add this to the documentation.

**Comment by mrsweaters** [comment]
@joaolavoier If I use the above config for Webpack, it then requires you to add `add-module-exports` to your project because the Tribute `.bablerc` requires it. Can this be removed from `.babelrc`?

**Comment by joaolavoier** [comment]
@mrsweaters Are you changing Browserify for Webpack? If yes, you can remove it, because this plugin `add-modules-exports` is to fix an error in Browserify import.

**Comment by mrsweaters** [comment]
I've updated the documentation to clarify how to use Tribute with Webpack.
