### ISSUE TITLE
Click event doesnt seem to be firing on mobile with custom menuItemTemplate

### ISSUE THREAD

**Issue by Alex61NN5** [zurb/tribute#260]
Hey There,

I am using tribute in my application, but I am using a custom `menuItemTemplate()` like so

```
menuItemTemplate: (item) => {
    return `
        <div class="user-mention-container">
            <img src="${item.original.avatar}" class="avatar">
            <div class="user-container">
                <p>${item.string}</p>
                <p class="user-email">${item.original.email}</p>
            </div>
        </div>
          `;
},
```

my css is as follows
```
.user-mention-container{
    display: flex;
}

.avatar{
   width: 50px; 
   height: 50px;
}

.user-mention-container .user-container{
    display: flex;
    flex-direction: column
}
```

now on desktop this works perfectly fine, but on mobile, The only way I can get the event to fire is if I click on the image, If I click anywhere else nothing happens

I have attached a codepen that shows the same issue on mobile.

https://codepen.io/alex61NN5/pen/OYpzRR

**Comment by adadgio** [comment]
How did you solve this ??

**Comment by Alex61NN5** [comment]
@adadgio I didn’t, I switched to a different package
