### ISSUE TITLE
Stop propagation when user hits enter

### ISSUE THREAD

**Issue by senky** [zurb/tribute#262]
**How can we reproduce this bug?**

1. Create an input with `onkeyup` listener.
2. Attach tribute to the input.
3. Select from mention suggestions using keyboard and hit enter.
4. `onkeyup` event is triggered.

**What did you expect to happen?**

I have an input which sends message when user hits enter. I want to add @mention capability so when user selects from the list, it is appended to the text, but won't send the message. So I either need an event which will help me stop my event or your library should stop propagation. Can this be done?

**Comment by mikerogne** [comment]
@senky why was this closed? did you find a solution?

**Comment by exzib** [comment]
I am also looking for an solution for this.
