### ISSUE TITLE
appendCurrent doesnt seem to do anything

### ISSUE THREAD

**Issue by syropian** [zurb/tribute#27]
I'm having trouble appending/replacing the items. Here's a little JSFiddle https://jsfiddle.net/jrpar74q/

Am I missing something obvious? I tried passing `true` as a second arg to replace the items, and that didn't work either.

**Comment by mrsweaters** [comment]
`appendCurrent` only works if there is an active instance of Tribute, meaning that someone has typed a trigger character and the menu is visible. Use `append` if there is no active instance.

**Comment by syropian** [comment]
@mrsweaters Looking at the source, it looks like both `append()` and `appendCurrent()` call a private `_append()` function that always checks if the menu is visible (see https://github.com/zurb/tribute/blob/master/src/Tribute.js#L251-L259)

**Comment by mrsweaters** [comment]
Ah! You are correct, that should actually be specific to `appendCurrent`. This is a bug.

**Comment by syropian** [comment]
Cool, thanks for confirming! I'm currently working on a VueJS wrapper for Tribute, so due to the way data would be passed to the plugin, I can simply manually replace all the data whenever it changes doing something like:

```js
setValues(values){
  // If it has a "values" property, it's actually a collection
  if( values.hasOwnProperty("values") ){
    this.tribute.collection = values;
  }
  else {
    this.tribute.collection[0].values = values;
  }
}
```

**Comment by mrsweaters** [comment]
@syropian Yeah that should work. Thanks for working on a wrapper for VueJS! When you're done, feel free to submit a PR to add it to the repo. That would be sweet!

**Comment by mrsweaters** [comment]
Fixed in 2.0.3!

**Comment by syropian** [comment]
Will do, how do you want me to go about creating a PR? Just a link in the README to the wrapper repo?

**Comment by mrsweaters** [comment]
Sure, that will be fine.

**Comment by ko06** [comment]
`setValues(values){
  // If it has a "values" property, it's actually a collection
  if( values.hasOwnProperty("values") ){
    this.tribute.collection = values;
  }
  else {
    this.tribute.collection[0].values = values;
  }
}`

it works but the menu still holding old data, once close it and open means its working fine
