### ISSUE TITLE
menu doesn't hide when noMatchTemplate setting value is null

### ISSUE THREAD

**Issue by zquancai** [zurb/tribute#288]
I think the following code is the problem.

```js
noMatchTemplate: (t => {
  if (typeof t === 'function') {
    return t.bind(this)
  }

  return noMatchTemplate || function () {return ''}.bind(this)
})(noMatchTemplate),
```

the noMatchTemplate is aways not equal null. so the follow code doesn't exec.

```js
if (!this.current.collection.noMatchTemplate) {
   // the code aways non-execution
    this.hideMenu()
} else {
    ul.innerHTML = this.current.collection.noMatchTemplate()
}
```

**Comment by zquancai** [comment]
I just reproduce in local, but not reproduce in codepen. 
because code in codepen not the same as master branch.

https://cdnjs.cloudflare.com/ajax/libs/tributejs/3.1.0/tribute.js
![image](https://user-images.githubusercontent.com/8609783/61505851-d0291f80-aa12-11e9-9a72-1029b80acf20.png)

**Comment by Postlagerkarte** [comment]
I believe that might already be fixed with my pull request #280 , which hasn't been merged yet

**Comment by zquancai** [comment]
> I believe that might already be fixed with my pull request #280 , which hasn't been merged yet

Cool! But I think you solution maybe not a best way to fix it, because someone want to return 0 or string 0 when no match. But this case not occur generally.

**Comment by Postlagerkarte** [comment]
You can return it like this

```
noMatchTemplate = function () { return "0"; },
```

Or do you have another use-case in mind?

**Comment by zquancai** [comment]
My mean is it must be exec when user use config with a no-match func, whatever what func is.

I just think you solution is a bit of complex. You can review my [code](https://github.com/zurb/tribute/pull/289/commits/9d6f0a9dff64198d90dd8749ea49188f4e1bf693#diff-5b3435b5541e95671e7c1ff53dbf4e7cL99) .

And you can config it by merge default config.

**Comment by Postlagerkarte** [comment]
@zquancai You code does not fix my initial issue ( it still shows an invisible menu instead of hiding it , which in turn leads to problems in multiline textareas and it does not work when a users adds a string as template  ).  I added test cases to my code to cover all scenarios with the noMatchTemplate.

**Comment by zquancai** [comment]
Ok, I see. Can you provide a codepen link? like [this](https://codepen.io/mrsweaters/pen/OxxdWv?editors=1010#0), that will be easy to reproduce this bug.
