### ISSUE TITLE
Highlight Class not applied when menuItemTemplate returns HTML

### ISSUE THREAD

**Issue by mlturner88** [zurb/tribute#296]
**How can we reproduce this bug?**

1. Create `menuItemTemplate` function that returns HTML (e.g. ```<div>${item.original.name}</div>```)
2. Add a background highlight CSS class for the `selectClass` option
3. Once the tribute menu opens, attempt to hover over the items

**What did you expect to happen?**
The CSS class provided to for the `selectClass` option to be applied to the tribute result.
**What happened instead?**
The CSS class is not applied to the tribute result (but is applied when using the keyboard arrows).
**Link (jsfiddle/plunkr/codepen) or Screenshot:**
https://codepen.io/mlturner/pen/eqEZYv
**Additional Note**
When I add extra padding to the `li` tags, the select class is applied when hover over the padded regions but not the provided `innerHTML`.

**Comment by jkhaui** [comment]
What I notice is the highlight actually is being applied if you move your mouse over an item; the issue is there's a lot of latency. E.g. try moving your mouse slowly from the first item to the bottom, and the highlight should be applied

I think the issue is caused by this code in /tribute.js

`            items.forEach((item, index) => {
                let li = this.range.getDocument().createElement('li')
                li.setAttribute('data-index', index)
                li.addEventListener('mousemove', (e) => {
                  let li = e.target;
                  let index = li.getAttribute('data-index')
                    if (e.movementY !== 0) {
                        this.events.setActiveLi(index)
                    }
                })
                if (this.menuSelected === index) {
                  li.className = this.current.collection.selectClass
                }
                li.innerHTML = this.current.collection.menuItemTemplate(item)
                fragment.appendChild(li)
            })
            ul.appendChild(fragment)
        }`

**Comment by mlturner88** [comment]
I agree. If the event target isn't the `li` element then it cannot find the index properly. I fixed this locally and can submit a PR if you want.

**Comment by jkhaui** [comment]
I don't maintain this library but have also had to hack part of the codebase myself to get it how I want. Glad to hear you got it solved.

**Comment by mlturner88** [comment]
All right I have a PR #297  that addresses this. Please let me know if anything needs to be updated or changed about it.

**Comment by mlturner88** [comment]
After my PR was merged this is fixed in version `3.7.2`
