### ISSUE TITLE
how to trigger tribute after @ + any letter

### ISSUE THREAD

**Issue by slnsrn** [zurb/tribute#30]
Hi, i am using tribute and it is all perfect! But now there is too much data and it is hard to start tribute after @/#.. Therefore i need to trigger mention or hashtag not just after @or #, but after an additional letter typing  like @a or #b?
Another issue is i want to use a dynamic mention list? 
How can i do that?

**Comment by mrsweaters** [comment]
@slnsrn This doesn't currently seem possible. As we are checkin on every keypress the value of the keypress. What is your use-case? Why can't you use one keypress?

**Comment by mrsweaters** [comment]
I'm closing this now as it seems like you were able to find a workaround. Feel free to open it back up and provide more details if you are still having issues.
