### ISSUE TITLE
Gulp was added to dependencies

### ISSUE THREAD

**Issue by poradz** [zurb/tribute#303]
**How can we reproduce this bug?**
Gulp was added to dependencies 

**What did you expect to happen?**
Merge https://github.com/zurb/tribute/pull/302

**What happened instead?**
Gulp exists in dependencies, which causes problems for dependency managment in open source projects such as YetiForceCRM.

**Comment by DanielRuf** [comment]
Hi @poradz,

What exact issues do you face?
> Gulp exists in dependencies, which causes problems for dependency managment in open source projects such as YetiForceCRM.

**Comment by mrsweaters** [comment]
Should be resolved now.
