### ISSUE TITLE
li elements not scrolling in tribute-container on arrow up/down

### ISSUE THREAD

**Issue by wacochili** [zurb/tribute#32]
We have more `li` elements in our list than will fit in the viewport of the fixed-height `tribute-container`. Scrolling with a mouse or trackpad works as expected, but arrow up/down does not move the list in the container.
1. Create a list of users larger than will fit in fixed height `tribute-container`
2. Trigger dropdown and arrow down to the bottom of the list (the list will not move with the arrow down behavior)
3. Try again with mouse or trackpad scroll and the list scrolls

We expected arrow up/down to move the list visually through viewport of the fixed height div.

We could hack this with javascript/jQuery but had expected arrow up/down to scroll out of the box.

**Comment by mrsweaters** [comment]
So this is an issue with the overflow of the container and you not being able to see the active `li` if it is beyond the height of the container? You expect it to scroll down to keep the active element visible in the menu container?

This makes sense to me.

**Comment by wacochili** [comment]
@mrsweaters Yes your understanding is correct.

**Comment by mrsweaters** [comment]
Ok great. I'll start working on a patch for that. Thank you for reporting!

**Comment by mrsweaters** [comment]
I haven't forgotten about this issue. I've been pretty busy as of late. This is the next issue I want to tackle.

**Comment by imransilvake** [comment]
is that fixed?
