### ISSUE TITLE
Autocomplete menu opened after complete

### ISSUE THREAD

**Issue by dgrubelic** [zurb/tribute#34]
**How can we reproduce this bug?**

1. Editor must be empty
2. Start mention with @
3. Hit enter to select first item or navigate using up/down keys and then hit enter

**What did you expect to happen?**
Autocomplete window closed

**What happened instead?**
Autocomplete window opened

**Link (jsfiddle/plunkr) or Screenshot:**
https://plnkr.co/edit/AV1ru1uYDbttp5mx62SF?p=preview

**Comment by mrsweaters** [comment]
This is a bug! Will look into it. Thank you for reporting!

**Comment by mrsweaters** [comment]
@dgrubelic What browser were you experiencing this bug in? I'm no longer able to reproduce it. Are you still seeing this issue?

**Comment by dgrubelic** [comment]
It is happening in both Chrome and Firefox (latest versions). Safari works as expected. I just slightly edited my Plunkr so you should be able to verify bug.

**Comment by raullucero** [comment]
What is the status of this bug?

**Comment by mrsweaters** [comment]
Fixed and released in [2.0.6](https://github.com/zurb/tribute/releases/tag/2.0.6). Thank you everyone for reporting!
