### ISSUE TITLE
Dropdown hover vs arrow highlighting

### ISSUE THREAD

**Issue by wacochili** [zurb/tribute#35]
When triggering the @mention dropdown, highlight is working as expected but the switching to and from mouse/trackpad navigation vs. arrow/keydown navigation the highlighted item doesn't switch properly.

1. Trigger dropdown
2. Arrow/keydown through the list
3. Scroll list with mouse/trackpad

We expect mouse navigation to behave the same as key navigation via arrows - the item hovered should clear the previously-highlighted item from being in it's highlighted state.

Instead 2 items can seemingly be highlighted at once and also when using the mouse/trackpad, again, as already mentioned, highlighted state will not clear. Hover is fine.

![hover](https://cloud.githubusercontent.com/assets/5550268/18839213/cb55cd08-83cf-11e6-953f-5730a9d05bdf.png)
![hover2](https://cloud.githubusercontent.com/assets/5550268/18839214/cb5a5008-83cf-11e6-8bec-6051ebcda310.png)

**Comment by mrsweaters** [comment]
@wacochili This has been fixed in master! Thanks again for reporting. I will be cutting a new release after I close down a couple more of the bugs. In the meantime you can use `master`.
