### ISSUE TITLE
Shipping an ES module build

### ISSUE THREAD

**Issue by stof** [zurb/tribute#352]
The readme describes this library as an ES6 mentions library.
While it is true that ES6 is used for contributors, users of the library only receive an UMD build. There is no `module` field in package.json pointing to an ES module build.

And this is quite unfortunate for webpack users (many projects out there), as webpack has a bunch of optimizations which are applied only for ES modules, not for CommonJS or UMD ones.

**Comment by mrsweaters** [comment]
@stof Thank you for your suggestion, this is a great idea. I would welcome a pull request adding this functionality. Would you mind doing a PR for this? Thanks!

**Comment by stof** [comment]
There is 2 ways to go for this:

1. pointing `module` to the original ES6 source code
2. pointing `module` to a bundle file using ES exports, while being processed for many other things

The option 1 is fine if your ES6 source code does not depend on unstable ES features. Someone needing to support older browsers could still configure their Babel to process the tribute code, but that would work easily (this is what material-component-web does for instance). This would still require a new major version though due to this need to transpile code in downstream project.
However, this option is a complete no-go if some unstable or non-standard features are used which would require a special build pipeline (as such special pipeline cannot be pushed to downstream projects).

Option 2 can be done in a minor release, as the produced ES code would have the same browser target than the UMD code (except for the exports themselves).

The current build process is based on browserify. I don't think it supports outputting ES modules right now. So going for option 2 would probably require switching to rollup (webpack will support ESM output only in the upcoming version 5).

Btw, a benefit of option 1 (if it is not ruled out due to non-standard features) is that projects can decide to ship native classes if their target browsers support them (as they would control the transpiling thanks to doing it downstream), which can allow for shorter code.

which option do you prefer ?

**Comment by mrsweaters** [comment]
@stof Thank you for the detailed options. I think option 1 would be the best approach to go with as it appears that most implementation these days have some form of transpiler in the build process.

**Comment by mrsweaters** [comment]
Done! We now have an ES Module build as of version 5.0.0.
