### ISSUE TITLE
Add ability to detach/remove a Tribute instance

### ISSUE THREAD

**Issue by jendowns** [zurb/tribute#37]
Hey there!

First of all, **thank you so much** for creating this plugin. I love it!

I was wondering if you'd consider an enhancement that allows me to completely remove an attached Tribute instance (so that I can then create a new instance with new data). 

In my use case, I have 2 Tribute instances attached to 2 textareas on a page (so one instance per textarea). When the user makes a selection above the first textarea, I want to replace the collection for the associated Tribute instance with completely new data without interfering with the other Tribute instance attached to the second textarea. 

Perhaps there could be "remove" method -- i.e., `tribute.remove(...)` to remove a Tribute instance from an element. That way, I could re-initialize & re-attach a new Tribute instance with new data to the target element.

What do you think?

Thank you for your time!

_Jen_

**Comment by mrsweaters** [comment]
This seems reasonable to me! You've outlined a good use case.

**Comment by kmyllyvi** [comment]
Hi.
Related to this, I'm just missing how to reset the data (values) in the tribute. Is there any way to do this? All I can find is append data.
thanks.

**Comment by mrsweaters** [comment]
@kmyllyvi `append` and `appendCurrent` both accept a replace boolean, if true, it will overwrite the data set already attached to the instance.
https://github.com/zurb/tribute/blob/master/src/Tribute.js#L292

**Comment by mrsweaters** [comment]
@jendowns I started working on a solution for this. It's not working right. Maybe you could take a look at the PR?

**Comment by philippkuehn** [comment]
Any news on this?

**Comment by mrsweaters** [comment]
I have the PR, but I would like someones review on it before I merge it in. I'm not sure if it covers all the bases.

**Comment by mrsweaters** [comment]
Detach is now available in `3.3.2`
