### ISSUE TITLE
Use the autocomplete mode with other separation characters than empty spaces

### ISSUE THREAD

**Issue by valentinstn** [zurb/tribute#393]
Usually, the autocomplete search is triggered always when a new word starts (i.e. after an empty space or at the start of the contenteditable div).

Is there a way to use other "separation characters" (like mathematical signs "+" or "-") to only use the parts after that sign for autocompletion search?

If no, I'd contribute something that adds it.

**Comment by mkrauskopf** [comment]
I've missed that option. Works like a charm. Thanks a lot!
