### ISSUE TITLE
error TS2339: Property 'showMenuForCollection' does not exist on type 'Tribute<Object>

### ISSUE THREAD

**Issue by inbukhari** [zurb/tribute#407]
I am using trinute with froala. I have a link that adds the # to the editor and then i want to trigger the tribute popup. for that i added a line

`this.tribute.showMenuForCollection(editor);`
but when the app compiles it throws an error "error TS2339: Property 'showMenuForCollection' does not exist on type 'Tribute<Object>" in console

My tribute declaration is 
`this.tribute = new Tribute(this.tributeOptions);`

and i am attaching it to froala 
`that.tribute.attach(editor.el);`

Also,
i see that there is an open merge request that could fix my error
https://github.com/zurb/tribute/pull/299/commits/c85dffbb0b8220c8c193a06653710c634e93edd9
Any ideas when this will get merged?

**Comment by mrsweaters** [comment]
Merged! Will release in 5.0.1
