### ISSUE TITLE
Only show menu after typing a few characters first? IE a minlength

### ISSUE THREAD

**Issue by dessalines** [zurb/tribute#418]
I've added an emoji autocomplete in my app with `:` 

The problem is, that I only want the menu to open after typing maybe 2 or 3 characters, not just `:` (since this is common text). I've tested emoji shortcode autocomplete with signal, discord, and matrix, and they all appear to require at least 3 characters before opening.

Is there any way to do this?

Code
```
  return new Tribute({
    collection: [
      // Emojis
      {
        trigger: ':',
        menuItemTemplate: (item: any) => {
          let emoji = `:${item.original.key}:`;
          return `${item.original.val} ${emoji}`;
        },
        selectTemplate: (item: any) => {
          return `:${item.original.key}:`;
        },
        values: Object.entries(emojiShortName).map(e => {
          return { key: e[1], val: e[0] };
        }),
        allowSpaces: false,
        autocompleteMode: true,
        menuItemLimit: mentionDropdownFetchLimit,
      },
...
```

**Comment by mrsweaters** [comment]
Can you check out this PR and see if it solves your problem:
https://github.com/zurb/tribute/pull/420

Adds support for `menuShowMinLength` option.

**Comment by dessalines** [comment]
Wow thanks! I'll comment again if I run into any issues.
