### ISSUE TITLE
The menu does not respond to the trigger after a non-space character.

### ISSUE THREAD

**Issue by mkrauskopf** [zurb/tribute#425]
**How can we reproduce this bug?**

1. Go to https://zurb.github.io/tribute/example/
2. In the first input, enter `@jo`, confirm "Jordan Humphreys" selection (press `Enter`)
3. Move one character back (press `left-arrow`)
4. Enter `/@` (that is, the final text is _Jordan Humphreys/@_`<cursor>`)

**What did you expect to happen?**
Tribute menu with the choices appears after the second trigger (`@`).

**What happened instead?**
The menu is not shown. The menu is shown only when the trigger (`@`) is entered after space/tab/new-line.

This issue is similar to (possibly the same as) #393. But the `autocomplete` is not needed here.

**Comment by mrsweaters** [comment]
Did you try setting `requireLeadingSpace` to false?

**Comment by mkrauskopf** [comment]
I've missed that option. Works like a charm. Thanks a lot! Closing.
