### ISSUE TITLE
could not attach tribute in a frame/body with contenteditable true created by CKEditor

### ISSUE THREAD

**Issue by thalesvinkler** [zurb/tribute#44]
**How can we reproduce this bug?**

1. Create textarea input
2. Set CKEditor in textarea -> its create a iframe with a body tag(contenteditable true)
3. try to attach: tribute.attach(document.getElementById('bodyid')

**What did you expect to happen?**
Attach tribute in body.

**What happened instead?**
Nothing

**Link (jsfiddle/plunkr) or Screenshot:**
![image](https://cloud.githubusercontent.com/assets/6230433/20805422/bb2b0924-b7dd-11e6-9abd-79cf430e71a5.png)

        `<script>
        CKEDITOR.replace( 'editor1' );
        //Criacao do Tribute AutoComplete
        var tribute = new Tribute({
            collection: [
                {
                    // The function that gets call on select that retuns the content to insert
                    selectTemplate: function (item) {
                        return '@[' + item.original.value + ']';
                    },
                    // template for displaying item in menu
                    menuItemTemplate: function (item) {
                        return '<img style="max-width: 20px;" src="'+ item.original.url + '">' + '&nbsp;&nbsp;&nbsp;&nbsp;' + item.original.value;
                    },
                    
                    // the array of objects
                    values: users,
                    
                    // specify whether a space is allowed in the middle of mentions
                    allowSpaces: false
                },
                {
                    // The symbol that starts the lookup
                    trigger: '#',
                    
                    // The function that gets call on select that retuns the content to insert
                    selectTemplate: function (item) {
                        return '#' + item.original.value;
                    },
                    
                    // template for displaying item in menu
                    menuItemTemplate: function (item) {
                        return item.original.value;
                    },
                    
                    // the array of objects
                    values: hashtags
                }
            ]
        })
        
        tribute.attach(document.querySelectorAll('.cke_editable'));
        //tribute.attach(document.getElementById('testarea'));
        //tribute.attach(document.querySelectorAll('#autocompletetext'));
        //tribute.attach(document.getElementsByTagName("p"));
        //
        
        //tribute.attach(document.getElementById("autocompletetext"));
        //tribute.attach(document.getElementsByTagName("body"));
        </script>`

**Comment by mrsweaters** [comment]
Thank you for reporting! We currently are compatible with WYSIWYG editors. We'd love some help to get this working if you are interested.

**Comment by mrsweaters** [comment]
@thalesvinkler This is a first pass, it still is a little rough:
https://github.com/zurb/tribute/pull/73

**Comment by mrsweaters** [comment]
I'm closing this issue as I'm not sure this is the direction we want to take the editor. If you build out a  solution that you would like to share I will link to it from the docs. I did start something in PR #73 that might be a good starting place for you!
