### ISSUE TITLE
Attach to SimpleMDE

### ISSUE THREAD

**Issue by raf66** [zurb/tribute#45]
Is it possible to attach Tribute to the Simple Markdown Editor "SimpleMDE"?
https://github.com/NextStepWebs/simplemde-markdown-editor

**Comment by mrsweaters** [comment]
Yes, this should be possible as the editor uses CodeMirror under the hood and doesn't rely on iframes. Tribute is not compatible with editors that rely on iframes.

**Comment by mrsweaters** [comment]
Feel free to reopen if you can't get it to work.

**Comment by SanderVanKeer** [comment]
I'm trying to attach Tribute to SimpleMDE. I tried to attach the tribute to the textarea in the CodeMirror. The tribute works fine until I select something from the list, the value is not shown in the textarea.
Do you know to what element I should attach the tribute in order for it to work? 

Thanks in advance!

**Comment by sf-john-kim** [comment]
Got it to work with EasyMDE (built on top of CodeMirror), but The backspace will not update the results, so once you hit backspace/delete, the content stops updating.

**Comment by juliangay** [comment]
@sf-john-kim Would you mind posting the snippet of how you attached Tribute to the editor?  Tx!
