### ISSUE TITLE
showMenuForCollection(input, 0, false) still inserts the @ 

### ISSUE THREAD

**Issue by Lee1984** [zurb/tribute#466]
**How can we reproduce this bug?**

    tribute.showMenuForCollection(input, 0, { addTrigger: false});

or

    tribute.showMenuForCollection(input, 0, false);

**What did you expect to happen?**

The @ symbol not to be inserted into our input field after we click a button to open the menu as per  #196 

**What happened instead?**

The `@` gets inserted. My collection object I set `trigger: "",` or leave it out but still it inserts the `@.`

**Link (jsfiddle/plunkr/codepen) or Screenshot:**

https://codepen.io/leee1984/pen/zYvjOYa?editors=1010

Anything wrong here?

**Comment by Lee1984** [comment]
Hey guys just seeing if there is any update on this? I don't have the skill to dig into the source code and check it out

**Comment by Lee1984** [comment]
This does work, I had a malfunctioning function before it.

**Comment by manikantayarramsetti1** [comment]
if i type del then it is suggesting two. they are

Delware
Rhode Island
But i want only delware to suggest, i dont want Rhode Island. I want to match with entire string not with characters
https://zurb.github.io/tribute/example/
can you try here
