### ISSUE TITLE
Request for Callback

### ISSUE THREAD

**Issue by snarkitect** [zurb/tribute#5]
We're using knockout, and It would be great to have a callback after text is replaced.  This isn't playing nicely with the textInput binding in knockoutjs, and it would help to be able to track the changes applied by tributejs.

**Comment by mrsweaters** [comment]
@snarkitect Does this solve your problem? https://github.com/zurb/tribute/pull/6

**Comment by snarkitect** [comment]
@mrsweaters Thanks for the quick response here. This would indeed solve the issue we're running into.

**Comment by mrsweaters** [comment]
No problem! Merged.
