### ISSUE TITLE
Declaration file required for Typescript

### ISSUE THREAD

**Issue by TetianaP** [zurb/tribute#52]
To use tribute withing Typescript - it is required to have a Declaration File. (tributejs.d.ts)

Can you please provide one?

**Comment by mrsweaters** [comment]
I don't use Typescript, so any help or direction on this would be much appreciated. This would be a great addition. Thanks!

**Comment by BorntraegerMarc** [comment]
any update on this? :)

**Comment by mrsweaters** [comment]
@BorntraegerMarc Thanks for checking in! I'm not quite sure how to write a typing but it doesn't seem too complicated. I can take a stab at it.

**Comment by BorntraegerMarc** [comment]
Thanks. Let me know if you need help

**Comment by TetianaP** [comment]
Since TypeScript 1.8, it's allowed to include .js files with `--allowJs` flag.
See [https://blogs.msdn.microsoft.com/typescript/2016/01/28/announcing-typescript-1-8-beta/](https://blogs.msdn.microsoft.com/typescript/2016/01/28/announcing-typescript-1-8-beta/)

Set `"compilerOptions": { "allowJs": true }`,
depending on your project structure include tribute library: `"include": ["node_modules/tributejs/dist/tribute.js"]`,
now you can use Tribute, just add `import {default as Tribute} from 'tributejs/dist/tribute'`;

**Comment by BorntraegerMarc** [comment]
Yes @TetianaP but it would be cool to have some definitely typed support for codin :)

**Comment by mrsweaters** [comment]
@TetianaP @BorntraegerMarc I've added a PR that adds a typings file to the project. Let me know if I need to make any changes!

**Comment by BorntraegerMarc** [comment]
@mrsweaters left my comments in the PR. Thx!

**Comment by mrsweaters** [comment]
Merged! https://github.com/zurb/tribute/pull/59

**Comment by BorntraegerMarc** [comment]
Sorry to come back at you this late but wouldn't it make more sense to publish the typings here https://github.com/DefinitelyTyped/DefinitelyTyped ?

I think this is standard practice...

**Comment by mrsweaters** [comment]
@BorntraegerMarc Ah, good call. I'll be sure to add this to the DefinitelyTyped repo.
