### ISSUE TITLE
'Utils' Script Missing from /dist

### ISSUE THREAD

**Issue by hew** [zurb/tribute#56]
**How can we reproduce this bug?**

1. `npm i --save tributejs`
2. `require('tributejs')`

**What did you expect to happen?**

Would import tributejs

**What happened instead?**

`dist/tribute.js` is requiring `./utils` on the 10th line, and that is not in the dist folder.

**Link (jsfiddle/plunkr) or Screenshot:**

![image](https://cloud.githubusercontent.com/assets/3103241/23483065/379aed5a-fe86-11e6-95dc-e8020edf3d68.png)

![image](https://cloud.githubusercontent.com/assets/3103241/23483129/859ba4fe-fe86-11e6-9961-a80b49838b84.png)

**Comment by mrsweaters** [comment]
Try `require('tributejs/src')`. Does that work?

**Comment by hew** [comment]
@mrsweaters That should work, but I'm not actually requiring manually. I'm trying to use https://github.com/BolsteDev/react-tribute, which makes use of tributejs as a dependency.

**Comment by mrsweaters** [comment]
Hmm, I'm not sure what the issue is there. It looks like [vue-tribute](https://github.com/syropian/vue-tribute/blob/master/src/index.js#L1) is successfully importing from root, I'm not sure with the React library isn't doing the same. For the Angular port, I just point it too the `src` directory. Maybe ask the react-tribute creators to do the same?

Let me know if there is anything I need to change on my end.

**Comment by mrsweaters** [comment]
What build environment are you using? Webpack?

**Comment by hew** [comment]
I'm pretty sure the issue is that `utils.js` is missing from the dist folder. It should be there, no?

https://github.com/zurb/tribute/blob/master/dist/tribute.js#L10

To be clear: whatever file is listed [here](https://github.com/zurb/tribute/blob/master/package.json#L5), is what will be used by default by other libraries.

**Comment by mrsweaters** [comment]
Fixed! Sorry for the long wait! https://github.com/zurb/tribute/commit/534d5e9551743f32ff8f57048dbbef43368ea97d

**Comment by dawgavins** [comment]
Hi there.  I just recently installed ('npm install tributejs'), and get this issue.  Its not just './utils' that is missing, but also './TributeEvents', './TributeSearch', everything that is imported at the top of tribute.js in the dist folder.  I am not using Webpack for this project.  Is Webpack a requirement?  Sorry if I'm naive, but how do these missing modules get imported when they are not in the dist directory?  Thanks.
