### ISSUE TITLE
Idea: Publish web component to use everywhere

### ISSUE THREAD

**Issue by BorntraegerMarc** [zurb/tribute#58]
Would be cool to have a web component published at http://webcomponents.org/  to use this component.

**Comment by mrsweaters** [comment]
@BorntraegerMarc This would be awesome! Would you be willing to help with that?

**Comment by BorntraegerMarc** [comment]
Hmm, time is very critical for me at the moment. For what do you need most help?

**Comment by mrsweaters** [comment]
No worries. Maybe just some understanding of what you are looking for? How you would imagine it working.

**Comment by BorntraegerMarc** [comment]
So basically I would imagine a standard web component (maybe build with [polymer](https://www.polymer-project.org/)

This web component would then use the standard methods from this library (because it uses just native JS it would be relatively easy to combine it) and would just expose the standard web component API.

Benefits:

- Standardized API from web components that all major frameworks already support
- Things like templates would need to be refactored based on the philosophy & API from web components. This way it would be really easy to customize the component to each use case

What I would envision is something published like https://www.webcomponents.org/element/PolymerElements/paper-input where the tribute component still would have easy customization but still supports all standard functions.

This [article](https://developers.google.com/web/fundamentals/getting-started/primers/customelements) gives a good introduction to custom elements.

Is it a bit more clear what I mean? :)

**Comment by BorntraegerMarc** [comment]
Maybe this would be something for version 3 @mrsweaters ? :)

**Comment by mrsweaters** [comment]
This would be great for V3!

**Comment by BorntraegerMarc** [comment]
Problem I'm seeing is that the whole library would need to be restructured to fit in web components world. Good thing though: then it could be truly used everywhere, in a very structured way!

Feel free to ask, if you need anything from my side and I'll see how much time I can allocate

**Comment by BorntraegerMarc** [comment]
@mrsweaters is there a plan for V4? Maybe we could aim for a complete re-write & support for web components in V4 😄

**Comment by mrsweaters** [comment]
Closing in favor of ES Modules for now.
