### ISSUE TITLE
Need access to original item key/value pairs after text is replaced

### ISSUE THREAD

**Issue by nathanchase** [zurb/tribute#62]
I see that I can access the 'tribute-replaced' event to get to the HTML inside `event.detail`, but what I really need access to are the original key/value pairs in my values collection.

For example, if I have:
```
values: [
     { name: "The Empire Strikes Back", id: "the-empire-strikes-back", entity: "movie" },
],
```
when my text is replaced, I need access to those original variables: **name**, **id**, and **entity** after my text has been replaced, because I'm going to need to store those variables in my object along with the replaced text.

(This allows me to display the "replaced" text when it's pulled from the database later and displayed in my app.)

So really, I just would like to see lines 101-103 in TributeRange.js:
```
        let replaceEvent = new CustomEvent('tribute-replaced', {
            detail: text
        })
```
changed to something along these lines:
```
        let replaceEvent = new CustomEvent('tribute-replaced', {
            detail: {
                 "text": text,
                 "name": name,
                 "id": id,
                 "entity": entity
            }
        })
```
The challenge is, I don't seem to have access to the `item` object at that point, and the code at that point would have no idea what the key/value pair names are, so you'd have to just iterate over them and deliver them directly - given that each item value could have any number of individual key/value pairs.

If you have a thought of how to accomplish this easily that I'm unaware of, let me know.

**Comment by nathanchase** [comment]
My hacky way to accomplish this in the meantime was to add `data-id="" data-name="" data-entity=""` to my select template HTML and then read them back as `item.dataset.id`, `item.dataset.name`, `item.dataset.entity`. It works, but seems convoluted.

**Comment by mrsweaters** [comment]
This is a great idea. I think that we need to pass the data back so that it works for any data structure. I'm willing to review a PR for this!

**Comment by mrsweaters** [comment]
Fixed: https://github.com/zurb/tribute/pull/71
