### ISSUE TITLE
Bug with contentedible, starting typing with @ and enter to select.

### ISSUE THREAD

**Issue by aldrakos** [zurb/tribute#63]
**How can we reproduce this bug?**
Using latest master version 2.3.6

1. Step one
Create a contentedible element:
```<div id="mention" contenteditable="true" placeholder="type here"></div>```
2. Step two
attach a tributejs with basic defaults (issue remains with custom selectTemplate):
```
let tribute = new Tribute({
        collection: [ {
          trigger: '@',
          allowSpaces: false,
          values: [{key: 'Phil Heartman', value: 'pheartman'}, {key: 'Gordon Ramsey', value: 'gramsey'}]
        }]
      });
tribute.attach(document.getElementById('mention'));
```

3. Step three
Start typing @ for the mention list to appear, select any, press enter (keyboard not click), and press space, or continue writing. Then press enter again.

**What did you expect to happen?**
Default action: in this case line change

**What happened instead?**
No default action, all text reverted to just mention. This also happened some time with text before the mention, and this text also disappeared (cannot reproduce though atm)

**Link (jsfiddle/plunkr) or Screenshot:**
[https://jsfiddle.net/kj2tzbe4/3/](https://jsfiddle.net/kj2tzbe4/3/)

**Comment by mrsweaters** [comment]
@aldrakos Thank you for reporting, I'll take a look at this now!

**Comment by mrsweaters** [comment]
So this looks like a bug with `allowSpaces`. If I turn that off I'm not seeing the issue. Is this what you are experiencing as well?

**Comment by mrsweaters** [comment]
Oh never mind, it looks like `allowSpaces` is not related.

**Comment by mrsweaters** [comment]
It was an issue with the default template. I have fixed it and will merge in https://github.com/zurb/tribute/pull/64

Again, thanks for reporting this!
