### ISSUE TITLE
TributeEvents can not be prevented from propagation

### ISSUE THREAD

**Issue by TetianaP** [zurb/tribute#65]
**How can we reproduce this bug?**

When `enter` event (to select item from dropdown) is fired, the events of element, which `tribute `is attached to, are still triggered.

**What did you expect to happen?**
Is it possible to have an option to stop propagation (event bubbling) of enter event?

**What happened instead?**
These is no way currently to get enter event, subscribe to it. The only emitted is custom `'tribute-replaced'` event, which unfortunately know nothing  about its parent event.
As possible solution `'tribute-replaced'` can provide its parent event, so we can call `stopPropagation `manually.

**Comment by mrsweaters** [comment]
@TetianaP I'll take a look at this. It sounds like a good solution to allow access to original event through the `tribute-replaced` event.

**Comment by mrsweaters** [comment]
Fixed with:
https://github.com/zurb/tribute/commit/dc89154fac26568254514f17f731013aa71c42dc
https://github.com/zurb/tribute/commit/1b7e45b73cc726949aec286147dc653749a01f6f
