### ISSUE TITLE
How to trigger AJAX and append results 

### ISSUE THREAD

**Issue by northernlite69** [zurb/tribute#66]
I think I've missed the docs on how to do this and I've trawled these issues but I still can't work out how to trigger an AJAX load.

I understand the expected format and how to append correctly, but I can't find how to hook Tribute to my AJAX load.

Great component! Any pointers much appreciated.

**Comment by mrsweaters** [comment]
@northernlite69 Did you get it working?

**Comment by northernlite69** [comment]
Yes!  Solution is triggered in no-match.  From here, grab cursor position back to trigger char, gives unfound search term, which can then be used to fetch new results from server.

I think I'm so used to everything being wrapped up for you!  Obviously a bad thing- I really like the openess of your component.  Thanks!

**Comment by mrsweaters** [comment]
Sweet!
