### ISSUE TITLE
Exception on choosing selection with no match

### ISSUE THREAD

**Issue by badz0** [zurb/tribute#665]
**How can we reproduce this bug?**

1. In tribute demo in the input with remote values enter something to get `no match` e.g `#dd` 
2. Hit tab or enter on your keyboard

**What did you expect to happen?**
Menu gets closed

**What happened instead?**
Exception

**Link (jsfiddle/plunkr/codepen) or Screenshot:**
![image](https://user-images.githubusercontent.com/12611322/117585330-85622580-b11a-11eb-9af8-b09948ca5404.png)

**Comment by mrsweaters** [comment]
This appears to be fixed, thank you!
