### ISSUE TITLE
Tribute in appendGrid?

### ISSUE THREAD

**Issue by northernlite69** [zurb/tribute#67]
Has anyone conquered getting Tribute working as a custom control in an appendGrid row?

In appendGrid you define a customBuilder: function that creates the dynamic control in a very jQuery stylee.  The problem is, with Tribute, you need an existing text input that's hooked via 

triLocation.attach(document.getElementById('txtFoo'));

or am I missing something?  Can you dynamically create individual Tributes?

**Comment by mrsweaters** [comment]
Looks like you could do it in a callback:
https://appendgrid.apphb.com/Documentation#link-afterRowInserted

**Comment by northernlite69** [comment]
Thanks for your swift reply (and all your work on a great component)!

I don't think afterRowInserted would work in this case; I believe this is more for massaging data AFTER the rows controls have been initialised.

Initialisation (of custom controls) happens before data even reaches any form elements and herein lies the catch.  Look at the example for the customBuilder and you will see what I mean:

https://appendgrid.apphb.com/Documentation#link-customBuilder

Thanks!

**Comment by mrsweaters** [comment]
I'm closing this issue for now as it is specific to a framework. If you find a workaround I'd be willing to add it to the readme. Thanks!
