### ISSUE TITLE
Memory Leak in TributeMenuEvents.js

### ISSUE THREAD

**Issue by omarstreak** [zurb/tribute#69]
In the bind function of TributeMenuEvents there's a call to document.addEventListener('click' and window.addEventListener('resize' .  These event listeners are never cleaned up (that I can see), even if the underlying text element is removed.

**Comment by mrsweaters** [comment]
Thanks for reporting! I'll take a look.

**Comment by mrsweaters** [comment]
@omarstreak Any suggestions on how to fix this?

**Comment by mrsweaters** [comment]
Detach is now available in `3.3.2`
