### ISSUE TITLE
Problems with shadow DOM

### ISSUE THREAD

**Issue by BorntraegerMarc** [zurb/tribute#76]
The call `this.getDocument().activeElement` in for example https://github.com/zurb/tribute/blob/060cf5f0b71c32dee9071fb4b4178a39cdde2cf3/src/TributeRange.js#L221 is causing problems when an app implements [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Shadow_DOM). Because the active element in shadow DOM is not the native input element but it's parent.

That is why all `this.getDocument().activeElement` should get replaced with `this.tribute.current.element`

@mrsweaters you know the architecture way better than me. Could you shortly explain why `this.getDocument().activeElement` was introduced instead of `this.tribute.current.element` and what implications it would had to replace it?

**Comment by mrsweaters** [comment]
I deployed your patch in 3.0.3. I'll see what's necessary to change all references to `this.getDocument().activeElement` changed to this.tribute.current.element.

**Comment by moshekarmel1** [comment]
Bump. Any update on this?

**Comment by moshekarmel1** [comment]
THANK YOU!!!!
