### ISSUE TITLE
No way to stop AJAX call

### ISSUE THREAD

**Issue by s-naveen** [zurb/tribute#78]
when using ajax request callback to populate values, The AJAX request is sent by adding a new character even after no match. There's no reason to send another request when the previous request with less characters itself returns nothing.

Also I would like to use the previously populated values instead of making new request again on pressing backspace.

**Comment by oliveratgithub** [comment]
FYI I have no problem with Tribute.js & AJAX calls - as proposed in the closed issue #93

**Comment by mrsweaters** [comment]
Closing as this is old and has been addressed.
