### ISSUE TITLE
Menu can get placed outside viewport

### ISSUE THREAD

**Issue by BorntraegerMarc** [zurb/tribute#79]
The menu is created with this call:
```
this.tribute = new Tribute({
            values: [],
            menuContainer: document.body,
            selectTemplate: (item) => {
                return '@' + item.original.value.username;
            },
            menuItemTemplate: (item) => {
                return 'someBoringHTML'
            },
            lookup: (original) => {
                return original.value.username + original.value.displayName;
            }
        });
```

We use this lib to display a user menu if somebody writes '@' in the message create input. As you can see from this screenshot (the menu to the very right bottom corner):
![untitled](https://user-images.githubusercontent.com/7549295/30033352-1115f884-919b-11e7-9e12-48e36e1d7175.png)

The tribute menu gets loaded nearly off screen. In this screenshot:
![untitled1](https://user-images.githubusercontent.com/7549295/30033353-111ef998-919b-11e7-837b-36741222c471.png)

It is even completely off screen. I think there should be an implementation, where the menu can never go outside the viewport. I can't think of an use case (not even iFrame?) where the menu should be outside the viewport...

**Comment by mrsweaters** [comment]
@BorntraegerMarc Your fix introduced a problem with floated elements, I've made some tweaks by factoring in the `offsetLeft` of the target element in version 3.1.1. Let me know if this causes you any problems.

**Comment by BorntraegerMarc** [comment]
alright, thanks for the info @mrsweaters

**Comment by lihi-intsights** [comment]
I updated to the version with this fix, and now the menu opens in a wrong place, but still goes outside of the viewport in some cases:

![image](https://user-images.githubusercontent.com/29015224/31317276-a17cb5dc-ac46-11e7-96da-8a09a052502c.png)

The left position is not in the right place, and the menu is outside of the viewport (vertically - in the bottom).
Maybe the problem is mine, I would like to know if it appears in other people's code.

Thanks!

**Comment by BorntraegerMarc** [comment]
That is possible @lihi-intsights
I didn't touch the vertical orientation, only horizontal one. So the element may be placed outside vertically.
