### ISSUE TITLE
How to use values from json

### ISSUE THREAD

**Issue by ismailhakkieren** [zurb/tribute#8]
first of all mey english isnot very good sorry for this. Iwant to use values form json but 
I try a lot of way but i couldnt do it. itry dataType json. jsonp not working list is empty. when i try html i can see values pattern on console just like yours. But icant get it. Console error arr.reduce is not a function

....
   return arr.reduce(function (prev, element, idx, arr) {
....

please help me my code is

$.ajax({
    type: 'GET',
    url: 'bla bla bla',
    dataType: 'html',
    success: function (data) {
        console.log(data)

        var tribute = new Tribute({
            values: JSON.stringify(data),
  
            selectTemplate: function (item) {
                if (this.range.isContentEditable(this.current.element)) {
                    return '<span contenteditable="false" class="mentionsPerson"><a href="http://ismailhakkieren.com" target="_blank" title="' + item.KEY + '" class="mentionsPerson">@' + item.KEY + '</a></span>';
                }
                return '@' + item.KEY;
            }
        });

        tribute.attach($('#mainEditor'));
        tribute.attach($('#inputExperience'));

      
    }
});

**Comment by ismailhakkieren** [comment]
[{"Key":"korhanerdem@gmail.com","Value":"","Email":"26","Picture":""},{"Key":"asen@avkom.com","Value":"Abdullah SEN","Email":"4","Picture":"/images/avatars/01390-5.png"},{"Key":"altuntas.avcm@gmail.com","Value":"Emine","Email":"21","Picture":"https://s3.amazonaws.com/bucket_d908dfab-6/member_9d96d97e-b/profilephotos/…GIPCMY2WR2FDOQ&Expires=2087630062&Signature=FNgrJehwYT9vQL7ngLq52wVDcKE%3D"},{"Key":"msultan@metus.com","Value":"Emir Sultan","Email":"1","Picture":"/images/avatars/01390-5.png"},{"Key":"ercan.ciftci@metus.com","Value":"ercan.ciftci","Email":"10","Picture":"https://bucket-d908dfab-6.s3.amazonaws.com/member_7bc3c538-8/profilephotos/…PCLVNPII3FNQEQ&Expires=2096106586&Signature=sgBhmtBulluLdn0wNbHUJEvuo1k%3D"},{"Key":"fatih.ilter@metus.com","Value":"Fatih ILTER","Email":"22","Picture":"/images/avatars/01390-5.png"},{"Key":"gorkem@kreatifajans.com","Value":"Görkem İsa Yıldırım","Email":"11","Picture":"/images/avatars/01390-5.png"},{"Key":"korhan.erdem@metus.com","Value":"Korhan Erdem","Email":"25","Picture":"/images/avatars/01430-7.png"},{"Key":"kubilaybayraktar@yahoo.com","Value":"kubi test","Email":"18","Picture":"/images/avatars/01390-5.png"},{"Key":"kubilay.bayraktar@metus.com","Value":"Kubilay","Email":"2","Picture":"/images/avatars/01390-2.png"},{"Key":"mehmet@photoclub.ws","Value":"Mehmet Sultan","Email":"5","Picture":"/images/avatars/01390-5.png"},{"Key":"mustafa.yilmaz@metus.com","Value":"Mustafa","Email":"6","Picture":"/images/avatars/01430-7.png"},{"Key":"oner.fidanci@metus.com","Value":"Öner Fidancı","Email":"8","Picture":"/images/avatars/01390-5.png"},{"Key":"oznr-gnyl@hotmail.com","Value":"öznur","Email":"20","Picture":"/images/avatars/01390-5.png"},{"Key":"test","Value":"test","Email":"24","Picture":"/images/avatars/01390-4.png"},{"Key":"zipekci@gmail.com","Value":"Zafer Ipekci","Email":"7","Picture":"/images/avatars/01390-5.png"}]

this is json

**Comment by mrsweaters** [comment]
Glad to help! `values` accepts an array of JSON objects, not a JSON string. So you should be able to just pass it the `data` object. 

If that doesn't help, create a [JSFiddle](https://jsfiddle.net/) or similar demonstrating your issue and I can debug it from there.

**Comment by ismailhakkieren** [comment]
i made it thanks.
data = JSON.parse(data);
