### ISSUE TITLE
Error in console when clicking on 'No Match' or clicking enter when there are no results

### ISSUE THREAD

**Issue by lihi-intsights** [zurb/tribute#80]
When typing something that doesn't exist on the values list and clicking on the 'No Match' in the list, an error appears in the console saying: 'Cannot read property 'original' of undefined'.

Does it should be clickable at all? there is no reason that someone could click the 'No Match' label that is shown when the typing did not match anything.

Also, the 'No Match' disappears after some chars where typed, and so the error is shown also when there isn't a 'No Match' label but the enter button is clicked.

**Comment by mrsweaters** [comment]
I would agree that the expected behavior is that it should not be clickable.

**Comment by lihi-intsights** [comment]
Is a fix going to be uploaded soon?
Thanks!

**Comment by mrsweaters** [comment]
I'm not going to be able to get to it myself this week, but I'm willing to review and merge a pull request.

**Comment by mrsweaters** [comment]
Fixed in https://github.com/zurb/tribute/releases/tag/3.1.0. Thank you!

**Comment by lihi-intsights** [comment]
Thank you!
