### ISSUE TITLE
Mentions menu goes out of vertical view

### ISSUE THREAD

**Issue by lihi-intsights** [zurb/tribute#85]
When opening the mentions menu in the bottom of the page, the menu goes out of the view and a scroll is added to the page.

I believe that the wanted behavior in case the menu is too long (when the "top" coordinates + the menu height is bigger than the page height), is that it should be opened upwards.

![image](https://user-images.githubusercontent.com/29015224/31705595-ad118a9e-b3ee-11e7-8cb0-cceac6f14de2.png)

![image](https://user-images.githubusercontent.com/29015224/31705626-d3074ab8-b3ee-11e7-9cb2-0a070829848c.png)

**Comment by mrsweaters** [comment]
This is a great idea. I will put this on the todo list for the next major release.

**Comment by mrsweaters** [comment]
Menu flipping was introduced in `3.3.0`.
