### ISSUE TITLE
Retrieve and append results from AJAX call - based on first characters after @...

### ISSUE THREAD

**Issue by oliveratgithub** [zurb/tribute#93]
Hi there,
I can't figure out how to properly execute my AJAX call based on the first character(s) after `@...` in Tribute, which I then query against the DB, in order to receive a list of results to append to the Tribute values list.

E.g.: when I type `@p` I already want to execute my AJAX function, which requests all results starting with `p*` from the database. When I type `@phi` it requests `phi*`, etc.
And for every request, all results returned should be appended to Tribute, in order to have these proposals in the dropdown menu.

From what I understand in the docs and some discussions in the issues, I need to use the `lookup: function(){}` setting - correct?

### Here's what I got so far:
```javascript
// Tribute
var tribute = new Tribute({
  values: [ ],
  lookup: function (){
    getUsernames(this.value);
  }
});
tribute.attach('texteditor'));

// AJAX request to get matching usernames
function getUsernames(search){
	var xhr = new XMLHttpRequest();
	xhr.open('GET', '/ajax/get/usernames/'+search, true);
	xhr.setRequestHeader('Content-Type', 'application/json');
	xhr.onload = function () {
		var usernames = JSON.parse(xhr.responseText);
		if (xhr.readyState == 4 && xhr.status == "200") {
			usernames.forEach(function(username) {
			    // Append results to Tribute
			    tribute.append(0,[
				{name: username},
			    ]);
			});
		} else {
			console.error('There was a problem with the XMLHttpRequest.');
		}
	}
	xhr.send(null);
}
```
(the AJAX query & results work properly, I verified that already by the way)

Thanks for any help!

P.s.: this seems to duplicate #66 - but there the final solution was not posted, so asking again :)

**Comment by mrsweaters** [comment]
The lookup config is used in fuzzy matching the results already in the Tribute collection. If you are wanting to filter your results returned from the backend based on the query string.

I've updated the documentation to outline an approach to fetching remote data, although there are definitely other ways you could approach this. 
https://github.com/zurb/tribute#loading-remote-data

Let me know if you need further help!

**Comment by oliveratgithub** [comment]
Perfect, thanks a lot @mrsweaters !

**Comment by mrsweaters** [comment]
No problem! I'm going to close the issue for now. Feel free to open it again if you have further issues.

**Comment by ashmlk** [comment]
Hello, I am facing this issue as well, I cannot get the data to load properly, currently my settings are:

```
	var tribute = new Tribute({
		values: function (search, cb) {
			getUsernames(search, users => cb(users))
		},
		menuItemTemplate: function (item) {
			return '<img src="'+item.original.img.url + '">' + item.original.name + " " + item.original.last;
		},
		selectTemplate: function (item) {
			return '@' + item.original.username;
		},
	});
	tribute.attach(document.getElementById("id_content"));

	function getUsernames(search, cb){
		var xhr = new XMLHttpRequest();
		xhr.open('GET', '/get/user/mentions?q='+search, true);
		xhr.setRequestHeader('Content-Type', 'application/json');
		xhr.onload = function () {
			var data = JSON.parse(xhr.responseText);
			cb(data);
			if (xhr.readyState == 4 && xhr.status == "200") {
				$.each(data, function(i, item) {
					tribute.append(0,[
						{
							name: item.first_name,
							last: item.last_name,
							username:item.username,
							img: item.image
						},
					]);
				});
			} else if (xhr.status === 403) {
				cb([]);
			}
		}
		xhr.send(null);
	}
```

But when I type a username I get an error: ` Unable to append to values, as it is a function` .

I followed this issue and the documentation but I cannot seem to get it working with my settings.
