### ISSUE TITLE
How do I implement AutoComplete without any specific trigger.

### ISSUE THREAD

**Issue by sujeetbuddiga** [zurb/tribute#94]
Hi, I'm trying to implement auto-complete without any specific trigger inside a text-box as we see in google search.

Please help me achieve this.

Thanks in advance :D

**Comment by mrsweaters** [comment]
You mean it auto fills in the current most accepted match? I'm not sure what a good approach for this would be, but I'd be willing to accept a PR adding the feature.

**Comment by oliveratgithub** [comment]
Not sure, but I think you @sujeetbuddiga might be looking for something more like krisk/fuse to achieve this?

**Comment by mrsweaters** [comment]
We do have an implementation of fuzzy search built into tribute, but it doesn't auto fill.

**Comment by MalayaliRobz** [comment]
I do a version of tribute that works as an autocomplete without any tigger. https://github.com/MalayaliRobz/tribute-autocomplete.

**Comment by MalayaliRobz** [comment]
@mrsweaters sure, I'm more than happy in merging this back into Tribute. I'll give a PR this week.

**Comment by mrsweaters** [comment]
Merged!

**Comment by manikantayarramsetti1** [comment]
if i type del then it is suggesting two. they are

Delware
Rhode Island
But i want only delware to suggest, i dont want Rhode Island. I want to match with entire string not with characters
https://zurb.github.io/tribute/example/
can you try here

**Comment by manikantayarramsetti1** [comment]
if i type del then it is suggesting two. they are

Delware
Rhode Island
But i want only delware to suggest, i dont want Rhode Island. I want to match with entire string not with characters
https://zurb.github.io/tribute/example/
can you try here
